//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using Busjehuren.Core.Repositories;
    using System;
    using System.Collections.Generic;

    public partial class Adre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adre()
        {
            this.People = new HashSet<Person>();
            this.Vestigings = new HashSet<Vestiging>();
        }
    
        public int Id { get; set; }
        public string Straat { get; set; }
        public string Huisnummer { get; set; }
        public string Postcode { get; set; }
        public string Plaats { get; set; }
        public Nullable<int> LandId { get; set; }
        public string Telefoonnummer { get; set; }
        public string Faxnummer { get; set; }
        public string Mobielnummer { get; set; }
    
        public virtual Destination Destination { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> People { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vestiging> Vestigings { get; set; }
    }
}
