//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CamperAanbiedingMetPrijzen
    {
        public int Id { get; set; }
        public int CamperId { get; set; }
        public System.DateTime PeriodeVan { get; set; }
        public System.DateTime PeriodeTot { get; set; }
        public Nullable<decimal> BasisPrijs { get; set; }
        public Nullable<decimal> InventarisPrijsPerPersoon { get; set; }
        public Nullable<decimal> InventarisPrijs { get; set; }
        public bool IsActief { get; set; }
        public Nullable<decimal> VluchtPrijsEuro { get; set; }
        public Nullable<decimal> VluchtTaxEuro { get; set; }
        public Nullable<decimal> KortingPercOpCamper { get; set; }
        public Nullable<decimal> KortingPercOpTotaal { get; set; }
        public Nullable<decimal> KortingOpVluchtEuro { get; set; }
        public Nullable<decimal> VastePrijsEuro { get; set; }
        public bool IsBestGeboekt { get; set; }
        public Nullable<decimal> BestGeboektPrijsEuro { get; set; }
        public Nullable<int> BestGeboektDuur { get; set; }
        public Nullable<decimal> VanafPrijs { get; set; }
        public int VestigingId { get; set; }
        public Nullable<decimal> Expr1 { get; set; }
    }
}
