//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Camper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Camper()
        {
            this.CamperAanbiedings = new HashSet<CamperAanbieding>();
            this.CamperBeds = new HashSet<CamperBed>();
            this.CamperBestandens = new HashSet<CamperBestanden>();
            this.CamperEigenschappens = new HashSet<CamperEigenschappen>();
        }
    
        public int Id { get; set; }
        public int Status { get; set; }
        public string Naam { get; set; }
        public int LeverancierId { get; set; }
        public decimal Lengte { get; set; }
        public decimal Breedte { get; set; }
        public decimal Hoogte { get; set; }
        public decimal InterieurHoogte { get; set; }
        public int MinAantPersonen { get; set; }
        public int MaxAantKinderen { get; set; }
        public int MaxAantVolwassenen { get; set; }
        public int MaxAantPersonen { get; set; }
        public Nullable<int> LaadHoogte { get; set; }
        public Nullable<int> LaadBreedte { get; set; }
        public Nullable<int> LaadLengte { get; set; }
        public Nullable<int> LaadVermogen { get; set; }
        public Nullable<int> LaadRuimte { get; set; }
        public int BrandstofCapaciteit { get; set; }
        public decimal BrandstofVerbruik { get; set; }
        public int WaterCapacteit { get; set; }
        public Nullable<decimal> Commissie { get; set; }
        public Nullable<decimal> CamperKorting { get; set; }
        public string Video { get; set; }
        public int DagIndelingBestandId { get; set; }
        public int NachtIndelingBestandId { get; set; }
        public string ExternalId { get; set; }
        public string UrlName { get; set; }
        public Nullable<int> Classification { get; set; }
    
        public virtual Leverancier Leverancier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CamperAanbieding> CamperAanbiedings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CamperBed> CamperBeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CamperBestanden> CamperBestandens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CamperEigenschappen> CamperEigenschappens { get; set; }
    }
}
