//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CamperEigenschappen
    {
        public int CamperId { get; set; }
        public int EigenschapId { get; set; }
        public int EigenschapWaardeId { get; set; }
    
        public virtual Camper Camper { get; set; }
        public virtual Eigenschap Eigenschap { get; set; }
        public virtual EigenschapWaarde EigenschapWaarde { get; set; }
    }
}
