//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Content()
        {
            this.SupplierContents = new HashSet<SupplierContent>();
        }
    
        public int Id { get; set; }
        public int LanguageId { get; set; }
        public Nullable<int> DestinationId { get; set; }
        public int TypeId { get; set; }
        public string DisplayName { get; set; }
        public string UrlName { get; set; }
        public string HeadText { get; set; }
        public string Text { get; set; }
        public string MetaTitle { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
        public Nullable<System.DateTime> LastEdited { get; set; }
        public string EditedBy { get; set; }
        public string Alias { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<int> ZoomLevel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierContent> SupplierContents { get; set; }
        public virtual ContentType ContentType { get; set; }
        public virtual Destination Destination { get; set; }
        public virtual Language Language { get; set; }
    }
}
