//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EigenschapWaarde
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EigenschapWaarde()
        {
            this.CamperEigenschappens = new HashSet<CamperEigenschappen>();
        }
    
        public int Id { get; set; }
        public int EigenschapId { get; set; }
        public string Waarde { get; set; }
        public string Bijzonderheden { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CamperEigenschappen> CamperEigenschappens { get; set; }
        public virtual Eigenschap Eigenschap { get; set; }
    }
}
