//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eigenschap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Eigenschap()
        {
            this.CamperEigenschappens = new HashSet<CamperEigenschappen>();
            this.EigenschapWaardes = new HashSet<EigenschapWaarde>();
        }
    
        public int Id { get; set; }
        public string Naam { get; set; }
        public bool IsFilterAttribuut { get; set; }
        public bool IsFastCheckFilterAttribuut { get; set; }
        public int Categorie { get; set; }
        public int Status { get; set; }
        public int Type { get; set; }
        public bool IsZoekResultaatEigenschap { get; set; }
        public bool IsUitrusting { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CamperEigenschappen> CamperEigenschappens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EigenschapWaarde> EigenschapWaardes { get; set; }
    }
}
