//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leverancier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Leverancier()
        {
            this.Campers = new HashSet<Camper>();
            this.SupplierContents = new HashSet<SupplierContent>();
            this.Longhires = new HashSet<Longhire>();
            this.Vestigings = new HashSet<Vestiging>();
        }
    
        public int Id { get; set; }
        public string Naam { get; set; }
        public int Status { get; set; }
        public Nullable<int> LogoId { get; set; }
        public Nullable<decimal> Commissie { get; set; }
        public string Prijsvoorwaarden { get; set; }
        public string Huurvoorwaarden { get; set; }
        public string Openingstijden { get; set; }
        public string Ophaalinformatie { get; set; }
        public string Inleverinformatie { get; set; }
        public string Transferinformatie { get; set; }
        public Nullable<decimal> Korting { get; set; }
        public Nullable<bool> PrijsPerPeriode { get; set; }
        public Nullable<bool> AddOneExtraDay { get; set; }
        public Nullable<bool> Vroegboekkorting { get; set; }
        public Nullable<decimal> Vbkpercentage { get; set; }
        public Nullable<int> Vbkdagen { get; set; }
        public Nullable<System.DateTime> VroegboekPeriodeStart { get; set; }
        public Nullable<System.DateTime> VroegboekPeriodeEind { get; set; }
    
        public virtual Bestand Bestand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Camper> Campers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierContent> SupplierContents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Longhire> Longhires { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vestiging> Vestigings { get; set; }
    }
}
