//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pakket
    {
        public int Id { get; set; }
        public string Naam { get; set; }
        public string UitgebreideOmschrijving { get; set; }
        public decimal Prijs { get; set; }
        public bool IsStandaardAan { get; set; }
        public bool IsLokaalTeBetalen { get; set; }
        public int VestigingId { get; set; }
        public int ValutaId { get; set; }
        public int PakketType { get; set; }
        public bool IsPerPersoon { get; set; }
        public Nullable<int> MilePackageAmount { get; set; }
        public Nullable<bool> isGratis { get; set; }
        public Nullable<System.DateTime> GratisVan { get; set; }
        public Nullable<System.DateTime> GratisTot { get; set; }
        public int MinAantalDagen { get; set; }
        public int MaxAantalDagen { get; set; }
        public Nullable<bool> IsAantal { get; set; }
        public Nullable<int> MaxAantal { get; set; }
        public Nullable<int> Aantal { get; set; }
        public string Image { get; set; }

        public virtual Valuta Valuta { get; set; }
        public virtual Vestiging Vestiging { get; set; }
    }
}
