//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreImportCamperPrice
    {
        public int Id { get; set; }
        public int LeverancierId { get; set; }
        public string LocationId { get; set; }
        public string CamperId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal Price { get; set; }
        public int PricTableId { get; set; }
        public Nullable<decimal> InventoryPricePP { get; set; }
        public Nullable<decimal> CamperInventoryPrice { get; set; }
    }
}
