//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierContent
    {
        public int Id { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> ContentId { get; set; }
    
        public virtual Content Content { get; set; }
        public virtual Leverancier Leverancier { get; set; }
    }
}
