//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_IpToCountry
    {
        public int intID { get; set; }
        public decimal intIP_From { get; set; }
        public decimal intIP_To { get; set; }
        public string strISO2 { get; set; }
        public string strISO3 { get; set; }
        public string strCountryDescription { get; set; }
    }
}
