//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Destinations
    {
        public int intID { get; set; }
        public Nullable<int> intParentID { get; set; }
        public string strUrlName { get; set; }
        public string strSeoName { get; set; }
        public string strBxName { get; set; }
        public Nullable<int> intDestinationType { get; set; }
        public Nullable<double> strLatitude { get; set; }
        public Nullable<double> strLongitude { get; set; }
        public Nullable<int> intZoomLevel { get; set; }
        public Nullable<bool> blnActive { get; set; }
        public Nullable<bool> blnTradeTrackerXml { get; set; }
        public Nullable<bool> blnTradeTrackerTopXml { get; set; }
        public Nullable<int> intWeerOnlineCountryID { get; set; }
        public Nullable<int> intWeerOnlineRegionID { get; set; }
        public Nullable<int> intWtcDesID { get; set; }
        public Nullable<int> intWtcHcID { get; set; }
        public Nullable<int> intWtcVtID { get; set; }
        public Nullable<int> intWtcHoID { get; set; }
        public Nullable<int> intImageCounter { get; set; }
        public Nullable<bool> blnFastcheck { get; set; }
        public string strIsoCode { get; set; }
    }
}
