//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CamperOffers
    {
        public int intID { get; set; }
        public Nullable<int> intDestinationID { get; set; }
        public string strTitle { get; set; }
        public string strShortDescription { get; set; }
        public string strDeepLink { get; set; }
        public Nullable<decimal> decPrice { get; set; }
        public Nullable<decimal> decDiscountPrice { get; set; }
        public Nullable<int> intCamperType { get; set; }
        public Nullable<System.DateTime> dtmOfferStart { get; set; }
        public Nullable<System.DateTime> dtmOfferEnd { get; set; }
    }
}
