//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbls_xmlfreetextfieldsedit
    {
        public int intPrimaryKeyID { get; set; }
        public int intXMLTypeID { get; set; }
        public int intLanguageID { get; set; }
        public string strFreeTextXML { get; set; }
        public int intStatusID { get; set; }
        public int intID { get; set; }
    }
}
