//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbls_Sessions
    {
        public string strGuid { get; set; }
        public string strObjectName { get; set; }
        public string txtValue { get; set; }
        public Nullable<System.DateTime> dtmCreate { get; set; }
    }
}
