//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbls_Xmltypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbls_Xmltypes()
        {
            this.tbls_CategoriesXmlTypes = new HashSet<tbls_CategoriesXmlTypes>();
            this.tbls_DropdownsXmlTypes = new HashSet<tbls_DropdownsXmlTypes>();
            this.tbls_Xmlfields = new HashSet<tbls_Xmlfields>();
        }
    
        public int intID { get; set; }
        public string strXMLTypeName { get; set; }
        public string txtXSDschema { get; set; }
        public string txtXMLschema { get; set; }
        public string txtXMLLanguageSchema { get; set; }
        public string txtXMLSearch { get; set; }
        public Nullable<int> intSystemTypeID { get; set; }
        public string strTableSearchField { get; set; }
        public string strXMLSearchfieldsTable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbls_CategoriesXmlTypes> tbls_CategoriesXmlTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbls_DropdownsXmlTypes> tbls_DropdownsXmlTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbls_Xmlfields> tbls_Xmlfields { get; set; }
    }
}
