//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbls_ImportJobs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbls_ImportJobs()
        {
            this.tbls_Importxml = new HashSet<tbls_Importxml>();
            this.tbls_ImportXmlLanguages = new HashSet<tbls_ImportXmlLanguages>();
        }
    
        public int intID { get; set; }
        public string strImportName { get; set; }
        public string strImportXML { get; set; }
        public Nullable<int> intXMLTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbls_Importxml> tbls_Importxml { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbls_ImportXmlLanguages> tbls_ImportXmlLanguages { get; set; }
    }
}
