//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbls_FailedLogins
    {
        public int intID { get; set; }
        public string strUserName { get; set; }
        public string strPassword { get; set; }
        public System.DateTime dtmTimestamp { get; set; }
        public string strIP { get; set; }
    }
}
