//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbls_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbls_Users()
        {
            this.tbls_UsersXML = new HashSet<tbls_UsersXML>();
            this.tbls_Roles = new HashSet<tbls_Roles>();
        }
    
        public int intID { get; set; }
        public string strUserName { get; set; }
        public string strPassword { get; set; }
        public Nullable<int> intGroupID { get; set; }
        public int blnEnabled { get; set; }
        public Nullable<System.DateTime> dtmLastLogin { get; set; }
        public int intLanguageID { get; set; }
        public int intFailedAttempts { get; set; }
    
        public virtual tbls_Groups tbls_Groups { get; set; }
        public virtual tbls_Languages tbls_Languages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbls_UsersXML> tbls_UsersXML { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbls_Roles> tbls_Roles { get; set; }
    }
}
