//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbls_ImportXmlLanguages
    {
        public int intID { get; set; }
        public int intImportJobID { get; set; }
        public int intLanguageID { get; set; }
        public Nullable<int> intPrimaryKeyID { get; set; }
        public Nullable<int> intImportStatusID { get; set; }
        public string txtOldImportLanguageXML { get; set; }
        public string txtNewImportLanguageXML { get; set; }
    
        public virtual tbls_ImportJobs tbls_ImportJobs { get; set; }
    }
}
