//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbls_Categories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbls_Categories()
        {
            this.tbls_Categoryancestors = new HashSet<tbls_Categoryancestors>();
            this.tbls_Categorylanguagevalues = new HashSet<tbls_Categorylanguagevalues>();
            this.tbls_Categoryparents = new HashSet<tbls_Categoryparents>();
        }
    
        public int intID { get; set; }
        public string strCategoryName { get; set; }
        public Nullable<int> intXmlTypeID { get; set; }
        public string strCategoryXML { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbls_Categoryancestors> tbls_Categoryancestors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbls_Categorylanguagevalues> tbls_Categorylanguagevalues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbls_Categoryparents> tbls_Categoryparents { get; set; }
    }
}
