//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbls_GroupsXML
    {
        public int intID { get; set; }
        public int intXMLTypeID { get; set; }
        public int intGroupID { get; set; }
        public string strGroupXML { get; set; }
    
        public virtual tbls_Groups tbls_Groups { get; set; }
    }
}
