//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbls_Groups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbls_Groups()
        {
            this.tbls_GroupsXML = new HashSet<tbls_GroupsXML>();
            this.tbls_Roles = new HashSet<tbls_Roles>();
            this.tbls_Users = new HashSet<tbls_Users>();
        }
    
        public int intID { get; set; }
        public string strGroupName { get; set; }
        public int intCountryID { get; set; }
        public int intGroupTypeID { get; set; }
        public Nullable<int> intParentID { get; set; }
    
        public virtual tbls_GroupsTypes tbls_GroupsTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbls_GroupsXML> tbls_GroupsXML { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbls_Roles> tbls_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbls_Users> tbls_Users { get; set; }
    }
}
