//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbls_Pages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbls_Pages()
        {
            this.tbls_Modules = new HashSet<tbls_Modules>();
            this.tbls_SecurityLevels = new HashSet<tbls_SecurityLevels>();
        }
    
        public int intID { get; set; }
        public string strPageName { get; set; }
        public Nullable<int> intParentID { get; set; }
        public Nullable<int> showMenuItem { get; set; }
        public Nullable<int> intOrderNumber { get; set; }
        public string strPageXML { get; set; }
        public Nullable<int> intGroup { get; set; }
        public int intSecurityLevel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbls_Modules> tbls_Modules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbls_SecurityLevels> tbls_SecurityLevels { get; set; }
    }
}
