//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbls_ModulesPermissions
    {
        public int intID { get; set; }
        public int intPermissionID { get; set; }
        public int intModuleID { get; set; }
    
        public virtual tbls_Modules tbls_Modules { get; set; }
        public virtual tbls_Permissions tbls_Permissions { get; set; }
    }
}
