//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbls_GroupsTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbls_GroupsTypes()
        {
            this.tbls_Groups = new HashSet<tbls_Groups>();
            this.tbls_Roles = new HashSet<tbls_Roles>();
        }
    
        public int intID { get; set; }
        public string strGroupTypeName { get; set; }
        public Nullable<int> intParentTypeID { get; set; }
        public int intSecurityLevelID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbls_Groups> tbls_Groups { get; set; }
        public virtual tbls_SecurityLevels tbls_SecurityLevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbls_Roles> tbls_Roles { get; set; }
    }
}
