//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbls_Xmlfields
    {
        public int intID { get; set; }
        public int intXMLTypeID { get; set; }
        public string strFieldName { get; set; }
        public string strXSDFieldType { get; set; }
        public string strDefaultValue { get; set; }
        public Nullable<int> intParentNodeID { get; set; }
        public Nullable<int> intXMLNodeTypeID { get; set; }
        public Nullable<int> blnLanguageField { get; set; }
        public Nullable<int> intMinOccurs { get; set; }
        public Nullable<int> intMaxOccurs { get; set; }
        public Nullable<int> intFieldTypeID { get; set; }
        public Nullable<int> intCategoryID { get; set; }
        public Nullable<int> intDropdownID { get; set; }
        public Nullable<int> intCategoryDepth { get; set; }
    
        public virtual tbls_Xmltypes tbls_Xmltypes { get; set; }
    }
}
