//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbls_ImportLog
    {
        public int intID { get; set; }
        public string txtLogXML { get; set; }
        public System.DateTime dtmLog { get; set; }
        public Nullable<int> intImportJobID { get; set; }
        public string strLogName { get; set; }
        public Nullable<int> intImportXmlID { get; set; }
    
        public virtual tbls_Importxml tbls_Importxml { get; set; }
    }
}
