//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbls_Importxml
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbls_Importxml()
        {
            this.tbls_ImportLog = new HashSet<tbls_ImportLog>();
        }
    
        public int intID { get; set; }
        public Nullable<int> intImportJobID { get; set; }
        public string txtOldImportXML { get; set; }
        public int intImportStatusID { get; set; }
        public int intPrimaryKeyID { get; set; }
        public string txtNewImportXML { get; set; }
        public string strExternalID { get; set; }
    
        public virtual tbls_ImportJobs tbls_ImportJobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbls_ImportLog> tbls_ImportLog { get; set; }
    }
}
