//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbls_Roles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbls_Roles()
        {
            this.tbls_PermissionsRoles = new HashSet<tbls_PermissionsRoles>();
            this.tbls_Users = new HashSet<tbls_Users>();
        }
    
        public int intID { get; set; }
        public string strRole { get; set; }
        public Nullable<int> intGroupID { get; set; }
        public string strRoleDescription { get; set; }
        public Nullable<int> intGroupTypeID { get; set; }
    
        public virtual tbls_Groups tbls_Groups { get; set; }
        public virtual tbls_GroupsTypes tbls_GroupsTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbls_PermissionsRoles> tbls_PermissionsRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbls_Users> tbls_Users { get; set; }
    }
}
