//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbls_SecurityLevels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbls_SecurityLevels()
        {
            this.tbls_GroupsTypes = new HashSet<tbls_GroupsTypes>();
        }
    
        public int intID { get; set; }
        public int intLevelNumber { get; set; }
        public Nullable<int> intStartPageID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbls_GroupsTypes> tbls_GroupsTypes { get; set; }
        public virtual tbls_Pages tbls_Pages { get; set; }
    }
}
