//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbls_Cache
    {
        public Nullable<int> intHash { get; set; }
        public string strQuery { get; set; }
        public string strResult { get; set; }
        public Nullable<int> intTouched { get; set; }
        public Nullable<int> intExecDuration { get; set; }
        public Nullable<System.DateTime> dtmLastTouched { get; set; }
        public Nullable<System.DateTime> dtmCreated { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
