//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbls_DomainSettings
    {
        public int intID { get; set; }
        public string strType { get; set; }
        public string strID { get; set; }
        public string strValue { get; set; }
        public string strDescription { get; set; }
    }
}
