//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbls_Languages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbls_Languages()
        {
            this.tbls_Dropdownlanguagevalues = new HashSet<tbls_Dropdownlanguagevalues>();
            this.tbls_Users = new HashSet<tbls_Users>();
        }
    
        public int intID { get; set; }
        public string strLanguage { get; set; }
        public string strLanguageDir { get; set; }
        public Nullable<int> blnDefaultLanguage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbls_Dropdownlanguagevalues> tbls_Dropdownlanguagevalues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbls_Users> tbls_Users { get; set; }
    }
}
