//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbls_Categorylanguagevalues
    {
        public int intID { get; set; }
        public int intCategoryID { get; set; }
        public int intLanguageID { get; set; }
        public string strDescription { get; set; }
    
        public virtual tbls_Categories tbls_Categories { get; set; }
    }
}
