//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vboekingen
    {
        public int BoekingId { get; set; }
        public string ReserveringsNummer { get; set; }
        public Nullable<double> TotaalPrijs { get; set; }
        public Nullable<int> AantalVolwassenen { get; set; }
        public Nullable<int> AantalKinderen { get; set; }
        public Nullable<System.DateTime> Ophaaldatum { get; set; }
        public Nullable<System.DateTime> Inleverdatum { get; set; }
        public Nullable<int> DuurInDagen { get; set; }
        public string OphaalLand { get; set; }
        public string OphaalVestiging { get; set; }
        public string OphaalBestemming { get; set; }
        public string InleverBestemming { get; set; }
        public string Camper { get; set; }
        public string CamperLeverancier { get; set; }
        public string VluchtBestemming { get; set; }
        public string BoekerNaam { get; set; }
        public string BoekerStad { get; set; }
        public string BoekerTelefoon { get; set; }
        public string BoekerEmail { get; set; }
        public bool HotelGeboekt { get; set; }
        public decimal AnnuleringsverzekeringPrijs { get; set; }
        public decimal ReisVerzekeringPrijs { get; set; }
        public decimal NoRiskVerzekeringPrijs { get; set; }
        public int Annuleringsverzekering { get; set; }
        public int Reisverzekering { get; set; }
        public int NoRiskverzekering { get; set; }
    }
}
