//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busjehuren.Core.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vestiging
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vestiging()
        {
            this.Pakkets = new HashSet<Pakket>();
            this.VestigingOpeningHours = new HashSet<VestigingOpeningHour>();
            this.CamperAanbiedings = new HashSet<CamperAanbieding>();
        }
    
        public int Id { get; set; }
        public int Status { get; set; }
        public string Naam { get; set; }
        public int BestemmingId { get; set; }
        public double Latitude { get; set; }
        public double Longtitude { get; set; }
        public int ZoomLevel { get; set; }
        public int AdresId { get; set; }
        public int LeverancierId { get; set; }
        public Nullable<int> ValutaId { get; set; }
        public Nullable<decimal> Korting { get; set; }
        public string ExternalId { get; set; }
        public Nullable<decimal> Tax { get; set; }
    
        public virtual Adre Adre { get; set; }
        public virtual Destination Destination { get; set; }
        public virtual Leverancier Leverancier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pakket> Pakkets { get; set; }
        public virtual Valuta Valuta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VestigingOpeningHour> VestigingOpeningHours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CamperAanbieding> CamperAanbiedings { get; set; }
    }
}
